name: 'Run ScalaTest'
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - dev-prerelease

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ScalaTestWindowsBasic:
    runs-on: windows-latest
    steps:
      - name: Checkout VerCors
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-10.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Run scalatest
        run: mill allTests.test vct.test.integration.examples.BasicExamplesSpec
      - name: Upload test reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-windows-latest
          path: '**/target/test-reports/TEST-*.xml'

  ScalaTestMacOsBasic:
    runs-on: macos-latest
    steps:
      - name: Checkout VerCors
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install clang
        run: brew install llvm
      - name: Run scalatest
        run: ./mill allTests.test vct.test.integration.examples.BasicExamplesSpec
      - name: Upload test reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-macos-latest
          path: '**/target/test-reports/TEST-*.xml'

  Compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout VerCors
      uses: actions/checkout@v2
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Compile
      run: ./mill allTests.deb
    - name: Upload allTests deb
      uses: actions/upload-artifact@v3
      with:
        name: allTestsDeb
        path: out/allTests/deb.dest/allTests-0.1-SNAPSHOT.deb

  ScalaTest:
    needs: "Compile"

    strategy:
      fail-fast: false
      matrix:
        batch: ["-n MATRIX[0]", "-n MATRIX[1]", "-n MATRIX[2]", "-n MATRIX[3]", "-n MATRIX[4]", "-n MATRIX[5]", "-n MATRIX[6]", "-n MATRIX[7]", "-l MATRIX"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout VerCors
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Download allTests deb
        uses: actions/download-artifact@v3
        with:
          name: allTestsDeb
          path: allTests.deb
      - name: Install allTests deb
        run: dpkg -i allTests.deb

      - name: Run scalatest for label ${{matrix.batch}}
        run: allTests -w vct ${{matrix.batch}}"

      - name: Upload test reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-ubuntu-latest-${{ matrix.batch }}
          path: '**/target/test-reports/TEST-*.xml'

  GenerateTestReport:
    runs-on: ubuntu-latest
    if: ${{ success() || failure() }}
    needs: [ScalaTest, ScalaTestWindowsBasic, ScalaTestMacOsBasic]

    steps:
    - name: Checkout VerCors
      uses: actions/checkout@v2

    - {name: Download Test Report ubuntu-0, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[0]", path: reports/ubuntu-0 }}
    - {name: Download Test Report ubuntu-1, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[1]", path: reports/ubuntu-1 }}
    - {name: Download Test Report ubuntu-2, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[2]", path: reports/ubuntu-2 }}
    - {name: Download Test Report ubuntu-3, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[3]", path: reports/ubuntu-3 }}
    - {name: Download Test Report ubuntu-4, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[4]", path: reports/ubuntu-4 }}
    - {name: Download Test Report ubuntu-5, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[5]", path: reports/ubuntu-5 }}
    - {name: Download Test Report ubuntu-6, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[6]", path: reports/ubuntu-6 }}
    - {name: Download Test Report ubuntu-7, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[7]", path: reports/ubuntu-7 }}
    - {name: Download Test Report ubuntu-x, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--l MATRIX", path: reports/ubuntu-x }}

    - { name: Download Test Report windows, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest", path: reports/windows } }
    - { name: Download Test Report macos, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest", path: reports/macos } }

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: TestReport           # Name of the check run which will be created
        path: 'reports/**/TEST-*.xml'    # Path to test results
        reporter: java-junit
